# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool: Test Pool 1

variables:
  buildConfiguration: 'Release'
  imageName: 'sample-app'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              repository: $(imageName)
              command: 'build'
              Dockerfile: 'Dockerfile'
              buildContext: '.'

