# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  repositories:
    - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
      type: github
      endpoint: vtoan
      name: vtoan/sample-app-net-6-manifests

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "3ca638e4-a02d-41b4-9ed1-187f3b2877f2"
  imageRepository: "vtoansampleappnet"
  containerRegistry: "testingacr1608.azurecr.io"
  dockerfilePath: "**/Dockerfile"
  tag: "$(Build.BuildId)"
  imagePullSecret: "testingacr16089886c249-auth"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool: Test Pool 1
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build

    jobs:
      - deployment: Deploy
        displayName: Deploy
        pool: Test Pool 1
        environment: "vtoansampleappnet6.default"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: MyGitHubRepo
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: createSecret
                    secretName: $(imagePullSecret)
                    dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: deploy
                    manifests: |
                      $(Build.SourcesDirectory)/deployment.yml
                      $(Build.SourcesDirectory)/service.yml
                    imagePullSecrets: |
                      $(imagePullSecret)
                    containers: |
                      $(containerRegistry)/$(imageRepository):$(tag)
