# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool: Test Pool 1

variables:
  buildConfiguration: 'Release'
  imageName: 'sample-app'
  # dockerRegistryServiceConnection: ""

stages:
  # - stage: Install
  #   displayName: Install dependencies stage
  #   jobs:
  #     - job: Install
  #       steps:
  #         - task: UseDotNet@2
  #            displayName: "Install .NET Core SDK"
  #            inputs:
  #              version: "6.x"
  #         - task: DockerInstaller@0
  #           inputs:
  #             dockerVersion: '17.09.0-ce'

  - stage: Build
    displayName: Build stage
    dependsOn: Install
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              repository: $(imageName)
              command: 'build'
              Dockerfile: 'Dockerfile'
              buildContext: '.'

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              path: 'manifests'
